Only complain about a missing "real" command when run is attempted.
Otherwise, it's not possible to wrap commands of a different name,
eg. a script called syzcmd that's a wrapper for modulecmd, because
they have to look something like:

    . shwrapnel
    shwrapnel set_real_cmd modulecmd
    shwrapnel launch

Bombing out on the first line isn't very useful.

diff --git a/bin/shwrapnel b/bin/shwrapnel
--- a/bin/shwrapnel
+++ b/bin/shwrapnel
@@ -279,6 +279,10 @@ function _shwrapnel_append_args {
 
 
 function _shwrapnel_run {
+	if [ "x$shwrapnel_real" = "x" ]; then
+		shwrapnel error 1 "shwrapnel: unable to find the 'real' $shwrapnel_cmdname" 1>&2
+	fi
+
 	local -a args
 	if [ $# -eq 0 ]; then
 		args=("${shwrapnel_args[@]}")
@@ -339,9 +343,6 @@ shwrapnel_args=("$@")
 
 
 shwrapnel findreal shwrapnel_orig_real shwrapnel_resolve_this
-if [ "x$shwrapnel_orig_real" = "x" ]; then
-	shwrapnel error 1 "shwrapnel: Error: Unable to find the 'real' $shwrapnel_cmdname" 1>&2
-fi
 shwrapnel_real="$shwrapnel_orig_real"
 
 
