Single 'shwrapnel' entry function lowers shell namespace pollution.

diff --git a/shwrapnel b/shwrapnel
--- a/shwrapnel
+++ b/shwrapnel
@@ -6,51 +6,57 @@ if test -z "$BASH_VERSION"; then
 fi
 
 
-function debug {
-	[ "x$shwrapnel_verbose" = "xy" -o "x$SHWRAPNEL_DEBUG" = "xy" ] && echo "$@" 1>&2
+function shwrapnel {
+	local fn="$1"
+	shift
+	_shwrapnel_$fn "$@"
 }
 
-function debug_var {
-	eval "debug \"${2:-$1}=\\\"\$$1\\\"\""
+function _shwrapnel_debug {
+	[ "x$shwrapnel_verbose" = "xy" -o "x$SHWRAPNEL_DEBUG" = "xy" ] && echo "shwrapnel: $@" 1>&2
 }
 
-function debug_array {
+function _shwrapnel_debug_var {
+	eval "shwrapnel debug \"${2:-$1}=\\\"\$$1\\\"\""
+}
+
+function _shwrapnel_debug_array {
 	local s
 	eval s="\${$1[@]}"
-	debug_var s "$1"
+	shwrapnel debug_var s "$1"
 }
 
-function force_message {
+function _shwrapnel_force_message {
 	#echo "$shwrapnel_cmdname wrapper: $@"
 	echo "$shwrapnel_cmdname: $@"
 }
 
-function message {
-	[ "x$shwrapnel_silent" != "xy" ] && force_message "$@"
+function _shwrapnel_message {
+	[ "x$shwrapnel_silent" != "xy" ] && shwrapnel force_message "$@"
 }
 
 shwrapnel_warnings=0
-function warning {
-	message "Warning: $@"
+function _shwrapnel_warning {
+	shwrapnel message "Warning: $@"
 	shwrapnel_warnings="$(($shwrapnel_warnings + 1))"
 }
 
-function error {
+function _shwrapnel_error {
 	local rc
 	rc="$1"
 	shift
-	force_message "Error: $@"
+	shwrapnel force_message "Error: $@"
 	exit "$rc"
 }
 
 
 shwrapnel_fullcmd="$0"
-debug_var shwrapnel_fullcmd
+shwrapnel debug_var shwrapnel_fullcmd
 shwrapnel_cmdname="${shwrapnel_fullcmd##*/}"
-debug_var shwrapnel_cmdname
+shwrapnel debug_var shwrapnel_cmdname
 # FIXME: remove fork
 shwrapnel_safe_cmdname="$(sed -e 's/[^A-Za-z0-9_]/_/g' <<< "$shwrapnel_cmdname")"
-debug_var shwrapnel_safe_cmdname
+shwrapnel debug_var shwrapnel_safe_cmdname
 
 eval shwrapnel_verbose="\${${shwrapnel_safe_cmdname}_wrapper_verbose:-n}"
 shwrapnel_verbose="${shwrapnel_verbose:-y}"
@@ -60,23 +66,23 @@ shwrapnel_silent="${shwrapnel_silent:-y}"
 
 declare -a shwrapnel_orig_args
 shwrapnel_orig_args=("$@")
-debug_array shwrapnel_orig_args
+shwrapnel debug_array shwrapnel_orig_args
 
 
-function findreal {
+function _shwrapnel_findreal {
 	local save_real="${1:-shwrapnel_real}"
 	local save_resolve_this="${2:-shwrapnel_resolve_this}"
 
 	local this="${3:-$shwrapnel_fullcmd}"
-	debug_var this
+	shwrapnel debug_var this
 	local resolve_this="$(readlink -f "$this")"
-	debug_var resolve_this
+	shwrapnel debug_var resolve_this
 	local target="${this##*/}"
-	debug_var target
+	shwrapnel debug_var target
 
-	debug_var shwrapnel_${shwrapnel_safe_cmdname}_prevwrap
+	shwrapnel debug_var shwrapnel_${shwrapnel_safe_cmdname}_prevwrap
 	IFS=: eval 'local -a prevwrap=(${shwrapnel_'"${shwrapnel_safe_cmdname}"'_prevwrap#:})'
-	debug_array prevwrap
+	shwrapnel debug_array prevwrap
 
 	local real=""
 	local candidates="$(type -all -path "$target")"
@@ -84,9 +90,9 @@ function findreal {
 	# but correcting that is too much work.
 	local i
 	for i in $candidates; do
-		debug_var i
+		shwrapnel debug_var i
 		local resolve_i="$(readlink -f "$i")"
-		debug_var resolve_i
+		shwrapnel debug_var resolve_i
 		if [ "$resolve_i" -ef "$resolve_this" ]; then
 			continue
 		fi
@@ -94,8 +100,8 @@ function findreal {
 		local found=n
 		local j
 		for j in "${prevwrap[@]}"; do
-			debug_var j
-			debug_var resolve_i
+			shwrapnel debug_var j
+			shwrapnel debug_var resolve_i
 			if [ "x$j" = "x$resolve_i" ]; then
 				found=y
 				break
@@ -107,44 +113,44 @@ function findreal {
 		fi
 	done
 
-	debug_var real
+	shwrapnel debug_var real
 	eval "$save_real=\"$real\""
 	eval "$save_resolve_this=\"$resolve_this\""
 }
 
-findreal shwrapnel_real shwrapnel_resolve_this
+shwrapnel findreal shwrapnel_real shwrapnel_resolve_this
 if [ "x$shwrapnel_real" = "x" ]; then
-	error 1 "Unable to find the 'real' $shwrapnel_cmdname" 1>&2
+	shwrapnel error 1 "shwrapnel: Error: Unable to find the 'real' $shwrapnel_cmdname" 1>&2
 fi
 
 
-function adjust_path_var {
+function _shwrapnel_adjust_path_var {
 	local var="$1"
 	local suffix="$2"
 	local fs_suffix="${3:-$suffix}"
-	debug "adjust_path_var: var=$var suffix=$suffix fs_suffix=$fs_suffix"
+	shwrapnel debug "adjust_path_var: var=$var suffix=$suffix fs_suffix=$fs_suffix"
 
 	local new=""
 
 	IFS=: eval 'local -a vals=(${!var})'
-	debug_array vals
+	shwrapnel debug_array vals
 
 	local i
 	for i in "${vals[@]}"; do
-		debug_var i
+		shwrapnel debug_var i
 		if [ "x$i" = "x" ]; then
 			i="."
 		fi
 		local basename="${i%/*}"
 		local dirname="${i##*/}"
-		debug "adjust_path_var: i=$i basename=$basename dirname=$dirname"
+		shwrapnel debug "adjust_path_var: i=$i basename=$basename dirname=$dirname"
 		if [ -d "$basename/$fs_suffix/$dirname" ]; then
 			new="$new:$basename/$fs_suffix/$dirname"
-			debug "adjust_path_var: found $basename/$fs_suffix/$dirname"
+			shwrapnel debug "adjust_path_var: found $basename/$fs_suffix/$dirname"
 		fi
 		if [ -d "$i/$fs_suffix" ]; then
 			new="$new:$i/$fs_suffix"
-			debug "adjust_path_var: found $i/$fs_suffix"
+			shwrapnel debug "adjust_path_var: found $i/$fs_suffix"
 		fi
 		new="$new:$i"
 	done
@@ -159,22 +165,22 @@ function adjust_path_var {
 	else
 		eval "$var=\"$special:$new\""
 	fi
-	debug_var $var
+	shwrapnel debug_var $var
 	export $var
 }
 
 
-function convert_path_var_to_cmdline_args {
+function _shwrapnel_convert_path_var_to_cmdline_args {
 	local var="$1"
 	local flag="$2"
 	local resultvar="${3:-opts}"
-	debug "convert_path_var_to_cmdline_args var=$var flag=$flag resultvar=$resultvar"
+	shwrapnel debug "convert_path_var_to_cmdline_args var=$var flag=$flag resultvar=$resultvar"
 
 	local -a result
 	IFS=: eval 'local -a vals=(${!var})'
 	local i
 	for i in "${vals[@]}"; do
-		debug_var i
+		shwrapnel debug_var i
 		if [ "x$i" = "x" ]; then
 			i="."
 		fi
@@ -184,11 +190,11 @@ function convert_path_var_to_cmdline_args {
 	done
 
 	eval "$resultvar="'("${result[@]}")'
-	debug_array $resultvar
+	shwrapnel debug_array $resultvar
 }
 
 
-function to_var_old {
+function _shwrapnel_to_var_old {
 	local newline='
 '
 	local maxlinelen="${GRAB_BOTH_MAXLINELEN:-1000}"
@@ -212,7 +218,7 @@ function to_var_old {
 	echo "$s"
 }
 
-function to_var {
+function _shwrapnel_to_var {
 	local newline='
 '
 	# the extra 256 is in case of quotes.
@@ -229,20 +235,20 @@ function to_var {
 	echo "$s$1+='${REPLY//\'/$protectedquote}'"
 }
 
-function grab_both {
+function _shwrapnel_grab_both {
 	local oname="$1" ; shift
 	local ename="$1" ; shift
 	local grab_both_rc
 	eval "$(
 		{
 			{
-				#"$@" | to_var_old "$oname" >&3
-				#"$@" | sed -e "s/'/'\''/g" | to_var "$oname" >&3
-				"$@" | to_var "$oname" >&3
+				#"$@" | shwrapnel to_var_old "$oname" >&3
+				#"$@" | sed -e "s/'/'\''/g" | shwrapnel to_var "$oname" >&3
+				"$@" | shwrapnel to_var "$oname" >&3
 				echo "grab_both_rc='${PIPESTATUS[0]}'" >&3
-			#} 2>&1 | to_var_old "$ename"
-			#} 2>&1 | sed -e "s/'/'\''/g" | to_var "$ename"
-			} 2>&1 | to_var "$ename"
+			#} 2>&1 | shwrapnel to_var_old "$ename"
+			#} 2>&1 | sed -e "s/'/'\''/g" | shwrapnel to_var "$ename"
+			} 2>&1 | shwrapnel to_var "$ename"
 		} 3>&1
 	)"
 	return $grab_both_rc
@@ -250,43 +256,43 @@ function grab_both {
 
 
 
-function do_launch {
-	debug exec "$@"                                                                                                          
+function _shwrapnel_do_launch {
+	shwrapnel debug exec "$@"                                                                                                          
 	exec "$@"                                                                                                          
 }
 
 
 
-function launch {
+function _shwrapnel_launch {
 	# The most common case of not needing to munge up the args
-	do_launch "$shwrapnel_real" "${shwrapnel_orig_args[@]}"
+	shwrapnel do_launch "$shwrapnel_real" "${shwrapnel_orig_args[@]}"
 }
 
-function launch_prepend {
+function _shwrapnel_launch_prepend {
 	# The next most common case of just prepending extra args
-	do_launch "$shwrapnel_real" "$@" "${shwrapnel_orig_args[@]}"
+	shwrapnel do_launch "$shwrapnel_real" "$@" "${shwrapnel_orig_args[@]}"
 }
 
-function launch_append {
+function _shwrapnel_launch_append {
 	# The next most common case of just appending extra args
-	do_launch "$shwrapnel_real" "${shwrapnel_orig_args[@]}" "$@"
+	shwrapnel do_launch "$shwrapnel_real" "${shwrapnel_orig_args[@]}" "$@"
 }
 
 
 
-debug_var shwrapnel_resolve_this
+shwrapnel debug_var shwrapnel_resolve_this
 eval "shwrapnel_${shwrapnel_safe_cmdname}_prevwrap=\"\${shwrapnel_${shwrapnel_safe_cmdname}_prevwrap}:\$shwrapnel_resolve_this\""
 export shwrapnel_${shwrapnel_safe_cmdname}_prevwrap
-debug_var shwrapnel_${shwrapnel_safe_cmdname}_prevwrap
+shwrapnel debug_var shwrapnel_${shwrapnel_safe_cmdname}_prevwrap
 
 eval shwrapnel_xloop="\${shwrapnel_${shwrapnel_safe_cmdname}_xloop:-0}"
-debug_var shwrapnel_xloop
+shwrapnel debug_var shwrapnel_xloop
 if [ "$shwrapnel_xloop" -eq "$$" ]; then
-	debug "Wrapper has already been run, short-circuiting" 1>&2
-	launch
+	shwrapnel debug "Wrapper has already been run, short-circuiting" 1>&2
+	shwrapnel launch
 fi
 export shwrapnel_${shwrapnel_safe_cmdname}_xloop=$$
-debug_var shwrapnel_${shwrapnel_safe_cmdname}_xloop
+shwrapnel debug_var shwrapnel_${shwrapnel_safe_cmdname}_xloop
 
 
 
